module.exports = {
    "starData": {
        "counts": [
            0,
            3,
            2,
            2,
            1,
            1
        ],
        "total": 9,
        "average": "2.4"
    },
    "reviewData": [
        {
            "productName": "Licensed Metal Pizza",
            "id": 23,
            "headline": "De-engineered holistic access",
            "body": "If we navigate the hard drive, we can get to the TCP interface through the back-end USB protocol!",
            "stars": 5,
            "posted": "2018-12-09T08:00:00.000Z",
            "helpful": 60,
            "verified": 0,
            "author_id": 15,
            "product_id": 71,
            "file": "http://lorempixel.com/640/480/city",
            "feature": null,
            "featureRating": null,
            "username": "Queenie.Johnson",
            "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/ipavelek/128.jpg"
        },
        {
            "productName": "Licensed Metal Pizza",
            "id": 37,
            "headline": "Fully-configurable coherent product",
            "body": "I'll input the mobile HTTP array, that should matrix the GB pixel!",
            "stars": 2,
            "posted": "2018-12-16T08:00:00.000Z",
            "helpful": 652,
            "verified": 0,
            "author_id": 74,
            "product_id": 71,
            "file": null,
            "feature": null,
            "featureRating": null,
            "username": "Cordia52",
            "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/nsamoylov/128.jpg"
        },
        {
            "productName": "Licensed Metal Pizza",
            "id": 91,
            "headline": "De-engineered multi-tasking open system",
            "body": "Try to input the COM array, maybe it will navigate the mobile application!",
            "stars": 3,
            "posted": "2018-10-23T07:00:00.000Z",
            "helpful": 631,
            "verified": 0,
            "author_id": 79,
            "product_id": 71,
            "file": null,
            "feature": null,
            "featureRating": null,
            "username": "Ayla.Lockman",
            "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/bargaorobalo/128.jpg"
        },
        {
            "productName": "Licensed Metal Pizza",
            "id": 112,
            "headline": "User-friendly client-driven help-desk",
            "body": "Use the neural GB bandwidth, then you can connect the multi-byte microchip!",
            "stars": 1,
            "posted": "2018-06-15T07:00:00.000Z",
            "helpful": 1101,
            "verified": 0,
            "author_id": 74,
            "product_id": 71,
            "file": null,
            "feature": null,
            "featureRating": null,
            "username": "Cordia52",
            "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/nsamoylov/128.jpg"
        },
        {
            "productName": "Licensed Metal Pizza",
            "id": 159,
            "headline": "Operative regional workforce",
            "body": "If we parse the interface, we can get to the TCP firewall through the online TCP transmitter!",
            "stars": 2,
            "posted": "2017-12-22T08:00:00.000Z",
            "helpful": 1068,
            "verified": 0,
            "author_id": 84,
            "product_id": 71,
            "file": null,
            "feature": null,
            "featureRating": null,
            "username": "Jennings_Mosciski8",
            "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/andreas_pr/128.jpg"
        },
        {
            "productName": "Licensed Metal Pizza",
            "id": 184,
            "headline": "Multi-lateral systematic help-desk",
            "body": "You can't bypass the system without indexing the primary COM matrix!",
            "stars": 1,
            "posted": "2018-11-28T08:00:00.000Z",
            "helpful": 874,
            "verified": 0,
            "author_id": 95,
            "product_id": 71,
            "file": null,
            "feature": null,
            "featureRating": null,
            "username": "Mattie_Cronin",
            "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/elenadissi/128.jpg"
        },
        {
            "productName": "Licensed Metal Pizza",
            "id": 188,
            "headline": "Operative homogeneous success",
            "body": "The SAS driver is down, reboot the mobile pixel so we can input the RSS microchip!",
            "stars": 3,
            "posted": "2018-08-28T07:00:00.000Z",
            "helpful": 1092,
            "verified": 1,
            "author_id": 72,
            "product_id": 71,
            "file": null,
            "feature": null,
            "featureRating": null,
            "username": "Gust_Wiegand68",
            "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/dingyi/128.jpg"
        },
        {
            "productName": "Licensed Metal Pizza",
            "id": 218,
            "headline": "Advanced client-driven database",
            "body": "If we quantify the circuit, we can get to the HDD protocol through the solid state ADP protocol!",
            "stars": 1,
            "posted": "2018-08-03T07:00:00.000Z",
            "helpful": 160,
            "verified": 1,
            "author_id": 83,
            "product_id": 71,
            "file": null,
            "feature": null,
            "featureRating": null,
            "username": "Janick25",
            "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/chrisslowik/128.jpg"
        },
        {
            "productName": "Licensed Metal Pizza",
            "id": 314,
            "headline": "Cloned clear-thinking encryption",
            "body": "The HDD sensor is down, input the back-end port so we can override the XML pixel!",
            "stars": 4,
            "posted": "2018-10-07T07:00:00.000Z",
            "helpful": 1141,
            "verified": 0,
            "author_id": 88,
            "product_id": 71,
            "file": null,
            "feature": null,
            "featureRating": null,
            "username": "Mateo89",
            "avatar": "https://s3.amazonaws.com/uifaces/faces/twitter/nbirckel/128.jpg"
        }
    ],
    "featureData": {}
}